// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFE9z34Up88cvn3pDeeboyGv6CkkmSVAk',
    appId: '1:330961362846:web:bb0e5aa0724b695a93408f',
    messagingSenderId: '330961362846',
    projectId: 'evnitypccoe',
    authDomain: 'evnitypccoe.firebaseapp.com',
    storageBucket: 'evnitypccoe.firebasestorage.app',
    measurementId: 'G-RKX9PHHLTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVuwx5buD0zL3RLS3EpN7VIgQjyV1ugM',
    appId: '1:330961362846:android:d7a4d122392cc62493408f',
    messagingSenderId: '330961362846',
    projectId: 'evnitypccoe',
    storageBucket: 'evnitypccoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEk0ahVbNu6ZHoYSjIrcofzMzjO0nAu0',
    appId: '1:330961362846:ios:888ebf91f9e633e893408f',
    messagingSenderId: '330961362846',
    projectId: 'evnitypccoe',
    storageBucket: 'evnitypccoe.firebasestorage.app',
    androidClientId: '330961362846-kkmih3kvfi46edjobnie1ab9c235cbca.apps.googleusercontent.com',
    iosClientId: '330961362846-2e1ua406niaualigcc85f4cjg2qqj112.apps.googleusercontent.com',
    iosBundleId: 'com.example.evnity',
  );

}
